package dmpro.character;

public enum CharacterManagementActions {
	INITIALIZECHARACTER,
	UPDATEXP,
	UPDATELEVEL,
	UPDATECOMBAT,
	UPDATESAVING,
	UPDATEHP,
	UPDATESPELLSALLOWED,
	UPDATESPELLBOOK,
	UPDATEDAILYSPELLS,
	UPDATETHIEFSKILLS,
	INITIALIZESPELLBOOK,
	INTIAILIZEEQUIPMENT,
	EQUIPCHARACTER,
	SPENDGOLD,
	INITIALIZEPROFICIENCIES,
	UPDATEPROFICIENCIES,
	ADDCHARACTERBACKGROUND,
	UPDATETURNUNDEAD;
}
